name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify
      working-directory: ./dream-log

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./dream-log/public

    - name: Deploy Pages artifact
      uses: actions/deploy-pages@v2